SET AUTOCOMMIT = 0;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN;
SELECT @x := (SELECT MIN(`salary`) FROM `employees`);
UPDATE `employees` SET `salary` = @x+5000 WHERE `salary`=@x;
COMMIT;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET AUTOCOMMIT = 1;
